from pathlib import Path

p = Path(__file__).with_name('phase8_warp_harness.cpp')
s = p.read_text(encoding='utf-8')
if 'warp_device_available' in s and 'a.pD3D12Device=nullptr' in s:
    raise SystemExit(0)

s = s.replace('    bool same_d3d12_device = false;\n', '''    bool warp_device_available = false;\n    bool underlying_adapter_found = false;\n    bool underlying_software = false;\n    std::string underlying_adapter;\n''')

s = s.replace('      << "  \\\"same_d3d12_device\\\": " << r.same_d3d12_device << ",\\n"\n', '''      << "  \\\"warp_device_available\\\": " << r.warp_device_available << ",\\n"\n      << "  \\\"underlying_adapter_found\\\": " << r.underlying_adapter_found << ",\\n"\n      << "  \\\"underlying_software\\\": " << r.underlying_software << ",\\n"\n      << "  \\\"underlying_adapter\\\": \\\"";\n    for(char c:r.underlying_adapter){ if(c=='\\\\'||c=='\\\"')f<<'\\\\'; f<<c; }\n    f << "\\\",\\n"\n''')

old = '''    ComPtr<IDXGIFactory4> factory; HRESULT hr=CreateDXGIFactory1(IID_PPV_ARGS(&factory)); if(FAILED(hr)){fail(R,"CreateDXGIFactory1 "+hrhex(hr));write_json(R);return 3;}\n    ComPtr<IDXGIAdapter> warp; hr=factory->EnumWarpAdapter(IID_PPV_ARGS(&warp)); if(FAILED(hr)){fail(R,"EnumWarpAdapter "+hrhex(hr));write_json(R);return 4;}\n    ComPtr<ID3D12Device> d12; hr=D3D12CreateDevice(warp.Get(),D3D_FEATURE_LEVEL_11_0,IID_PPV_ARGS(&d12)); if(FAILED(hr)){fail(R,"D3D12CreateDevice(WARP) "+hrhex(hr));write_json(R);return 5;}\n    D3D12_COMMAND_QUEUE_DESC qd{}; qd.Type=D3D12_COMMAND_LIST_TYPE_DIRECT; ComPtr<ID3D12CommandQueue> queue; hr=d12->CreateCommandQueue(&qd,IID_PPV_ARGS(&queue)); if(FAILED(hr)){fail(R,"CreateCommandQueue "+hrhex(hr));write_json(R);return 6;}\n\n    HMODULE d3d9dll=LoadLibraryW(L"d3d9.dll"); if(!d3d9dll){fail(R,"LoadLibrary(d3d9.dll)");write_json(R);return 7;}\n    auto create9on12=(PFN_Direct3DCreate9On12)GetProcAddress(d3d9dll,"Direct3DCreate9On12"); if(!create9on12){fail(R,"Direct3DCreate9On12 export missing");write_json(R);return 8;}\n    D3D9ON12_ARGS a{}; a.Enable9On12=TRUE; a.pD3D12Device=d12.Get(); a.ppD3D12Queues[0]=queue.Get(); a.NumQueues=1; a.NodeMask=0;\n'''
new = '''    ComPtr<IDXGIFactory4> factory; HRESULT hr=CreateDXGIFactory1(IID_PPV_ARGS(&factory)); if(FAILED(hr)){fail(R,"CreateDXGIFactory1 "+hrhex(hr));write_json(R);return 3;}\n    // WARP availability is checked independently. Do not inject the WARP D3D12 device into\n    // a D3D9 display adapter with a different LUID: that override is not applicable.\n    ComPtr<IDXGIAdapter> warp; ComPtr<ID3D12Device> warp12;\n    if(SUCCEEDED(factory->EnumWarpAdapter(IID_PPV_ARGS(&warp))) &&\n       SUCCEEDED(D3D12CreateDevice(warp.Get(),D3D_FEATURE_LEVEL_11_0,IID_PPV_ARGS(&warp12)))) R.warp_device_available=true;\n\n    HMODULE d3d9dll=LoadLibraryW(L"d3d9.dll"); if(!d3d9dll){fail(R,"LoadLibrary(d3d9.dll)");write_json(R);return 7;}\n    auto create9on12=(PFN_Direct3DCreate9On12)GetProcAddress(d3d9dll,"Direct3DCreate9On12"); if(!create9on12){fail(R,"Direct3DCreate9On12 export missing");write_json(R);return 8;}\n    // Documented catch-all 9On12 override: 9On12 creates the D3D12 device/queue for the\n    // active D3D9 display adapter selected by CreateDevice.\n    D3D9ON12_ARGS a{}; a.Enable9On12=TRUE; a.pD3D12Device=nullptr; a.ppD3D12Queues[0]=nullptr; a.ppD3D12Queues[1]=nullptr; a.NumQueues=0; a.NodeMask=0;\n'''
if old not in s:
    raise SystemExit('create block not found')
s = s.replace(old, new)

old = '''    ComPtr<ID3D12Device> returned12; hr=on12->GetD3D12Device(IID_PPV_ARGS(&returned12)); if(FAILED(hr)){fail(R,"GetD3D12Device "+hrhex(hr));write_json(R);return 12;}\n    ComPtr<IUnknown> i1,i2; d12.As(&i1); returned12.As(&i2); R.same_d3d12_device=(i1.Get()==i2.Get());\n    if(!R.same_d3d12_device){fail(R,"9On12 did not return supplied WARP D3D12 device");write_json(R);return 13;}\n\n'''
new = '''    ComPtr<ID3D12Device> returned12; hr=on12->GetD3D12Device(IID_PPV_ARGS(&returned12)); if(FAILED(hr)){fail(R,"GetD3D12Device "+hrhex(hr));write_json(R);return 12;}\n    LUID luid=returned12->GetAdapterLuid();\n    for(UINT n=0;;n++) {\n        ComPtr<IDXGIAdapter1> ad; HRESULT ehr=factory->EnumAdapters1(n,&ad); if(ehr==DXGI_ERROR_NOT_FOUND) break; if(FAILED(ehr)) break;\n        DXGI_ADAPTER_DESC1 d{}; if(SUCCEEDED(ad->GetDesc1(&d)) && d.AdapterLuid.HighPart==luid.HighPart && d.AdapterLuid.LowPart==luid.LowPart) {\n            R.underlying_adapter_found=true; R.underlying_software=(d.Flags & DXGI_ADAPTER_FLAG_SOFTWARE)!=0;\n            char name[256]{}; WideCharToMultiByte(CP_UTF8,0,d.Description,-1,name,sizeof(name),nullptr,nullptr); R.underlying_adapter=name; break;\n        }\n    }\n    if(!R.underlying_adapter_found){fail(R,"could not match 9On12 D3D12 adapter LUID");write_json(R);return 13;}\n\n'''
if old not in s:
    raise SystemExit('identity block not found')
s = s.replace(old, new)
s = s.replace('R.ok=rr&&R.on12&&R.same_d3d12_device&&R.state_restore&&R.blend_response&&R.normal_response&&R.ao_response&&R.roughness_response&&R.specular_response;', 'R.ok=rr&&R.on12&&R.underlying_adapter_found&&R.state_restore&&R.blend_response&&R.normal_response&&R.ao_response&&R.roughness_response&&R.specular_response;')
s = s.replace('std::cout << "D3D9On12 WARP=" << R.on12 << " sameD3D12=" << R.same_d3d12_device << " stateRestore=" << R.state_restore << "\\n";', 'std::cout << "D3D9On12=" << R.on12 << " WARP12Available=" << R.warp_device_available << " adapter=\\\"" << R.underlying_adapter << "\\\" software=" << R.underlying_software << " stateRestore=" << R.state_restore << "\\n";')
p.write_text(s, encoding='utf-8')
